### PR TITLE
Cleanup and custom Dockerfile

### PR DESCRIPTION
**Pull request by code-later**
These are the changes I made to match up the overhauled guide.

### CODE REVIEW

**Comment by zeisss** [comment]
How is the `rake db:migrate` achieved now?

**Comment by zeisss** [comment]
Thx btw :)

**Comment by code-later** [comment]
@ZeissS `rake db:migrate` is still present in the custom start script. I only replaced the arcane database creation with `rake db:create` :-)

**Comment by zeisss** [comment]
Ok, cool! LGTM

**Comment by code-later** [comment]
Thanks, any other comments? Or should I just merge this?

**Comment by zeisss** [comment]
Nope, fine with me.

**Pull request merged**
